root -l -b -q HistFitterqcd.C
root -l -b -q HistFitterqcdEl.C
root -l -b -q HistFitterGstartT_MG1000MT600_TtZ.C
root -l -b -q HistFitterGstartT_MG1000MT600_TWb.C   
root -l -b -q HistFitterGstartT_MG1000MT600_TtH.C   
root -l -b -q HistFitterGstartT_MG2000MT1400_TWb.C   
root -l -b -q HistFitterGstartT_MG2000MT1400_TtH.C    
root -l -b -q HistFitterGstartT_MG2000MT1400_TtZ.C
root -l -b -q HistFitterData.C
root -l -b -q HistFitterDiboson.C
root -l -b -q HistFitterSingleTop.C
root -l -b -q HistFitterWj.C
root -l -b -q HistFitterZj.C
root -l -b -q HistFitterttbar.C
root -l -b -q HistFitterttbarBoson.C 
root -l -b -q HistFitterGstartT_MG1000MT600_TtZEl.C
root -l -b -q HistFitterGstartT_MG1000MT600_TWbEl.C
root -l -b -q HistFitterGstartT_MG1000MT600_TtHEl.C
root -l -b -q HistFitterGstartT_MG2000MT1400_TWbEl.C
root -l -b -q HistFitterGstartT_MG2000MT1400_TtHEl.C
root -l -b -q HistFitterGstartT_MG2000MT1400_TtZEl.C
root -l -b -q HistFitterDataEl.C
root -l -b -q HistFitterDibosonEl.C
root -l -b -q HistFitterSingleTopEl.C
root -l -b -q HistFitterWjEl.C
root -l -b -q HistFitterZjEl.C
root -l -b -q HistFitterttbarEl.C
root -l -b -q HistFitterttbarBosonEl.C
