#gKK->ttbar
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_115550.*/*>input_Gtt_MG500.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_115551.*/*>input_Gtt_MG600.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_115552.*/*>input_Gtt_MG700.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_115553.*/*>input_Gtt_MG800.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_119318.*/*>input_Gtt_MG900.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_115554.*/*>input_Gtt_M1000.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_119319.*/*>input_Gtt_MG1150.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_115555.*/*>input_Gtt_MG1300.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_115556.*/*>input_Gtt_MG1600.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_115799.*/*>input_Gtt_MG1800.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_119582.*/*>input_Gtt_MG2000.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_158768.*/*>input_Gtt_MG2550.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_158769.*/*>input_Gtt_MG2500.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_180575.*/*>input_Gtt_MG2750.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_180576.*/*>input_Gtt_MG3000.txt
#gKK->tT
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_203054.GstartT_MG1000MT600_TWb_*/*>input_GstartT_MG1000MT600_TWb.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_203055.GstartT_MG1000MT600_TtZ_*/*>input_GstartT_MG1000MT600_TtZ.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_203056.GstartT_MG1000MT600_TtH_*/*>input_GstartT_MG1000MT600_TtH.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_203057.GstartT_MG2000MT1400_TWb_*/*>input_GstartT_MG2000MT1400_TWb.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_203058.GstartT_MG2000MT1400_TtZ_*/*>input_GstartT_MG2000MT1400_TtZ.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_203059.GstartT_MG2000MT1400_TtH_*/*>input_GstartT_MG2000MT1400_TtH.txt
#SingleTop
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_110090.SingleTop_*/*>input_SingleTop.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_110091.SingleTop_*/*>>input_SingleTop.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_110119.SingleTop_*/*>>input_SingleTop.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_110140.SingleTop_*/*>>input_SingleTop.txt
#117050.ttbar
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_117050.*/*>input_ttbar.txt
#110404.ttbar
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_110404.*/*>input_ttbar2.txt 
#ttbarBoson
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_119355.ttZ_*/*>input_ttbarBoson.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_119356.ttZ_*/*>>input_ttbarBoson.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_119353.ttW_*/*>>input_ttbarBoson.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_119354.ttW_*/*>>input_ttbarBoson.txt
#Diboson
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_105985.DiBoson_*/*>input_Dibosons.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_105986.DiBoson_*/*>>input_Dibosons.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_105987.DiBoson_*/*>>input_Dibosons.txt
#highPtWj
#ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_*.highptWj_btagjfit_SeljetIsNotbtag_JESComp_1Fj4Sj_tree.root/*>input_highptWj.txt
#Wj
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147025.Wj_*/*>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147026.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147027.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147028.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147029.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147030.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147033.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147034.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147035.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147036.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147037.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147038.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147041.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147042.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147043.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147044.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147045.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147046.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200056.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200057.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200058.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200059.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200060.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200156.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200157.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200158.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200159.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200256.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200257.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200258.Wj_*/*>>input_Wj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200259.Wj_*/*>>input_Wj.txt
#Zj
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147105.Zj_*/*>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147106.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147107.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147108.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147109.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147110.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147113.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147114.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147115.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147116.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147117.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147118.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147121.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147122.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147123.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147124.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147125.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_147126.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200332.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200333.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200334.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200335.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200340.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200341.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200342.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200343.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200348.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200349.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200350.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200351.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200432.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200433.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200434.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200435.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200440.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200441.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200442.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200443.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200448.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200449.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200450.Zj_*/*>>input_Zj.txt
ls eos/atlas/user/d/dshoaleh/user.dshoaleh.ttunf8TeV_200451.Zj_*/*>>input_Zj.txt
